//General actions
export const FILL_OUT_FORM = 'FILL_OUT_FORM'
export const CHANGE_ACTIVE = 'CHANGE_ACTIVE'
export const SWITCH_AUTH = 'SWITCH_AUTH'

//Auth actions
export const REGISTERING_USER = 'REGISTERING_USER'
export const LOGGING_IN_USER = 'LOGGING_IN_USER'
export const REGISTERED_SUCCESSFULLY = 'REGISTERED_SUCCESSFULLY'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'

//Tracking actions
export const TRACKING_PRODUCT = 'TRACKING_PRODUCT'
export const TRACKED_PRODUCT = 'TRACKED_PRODUCT'

//Shipment actions
export const CREATING_SHIPMENT = 'CREATING_SHIPMENT'
export const CREATING_DOCUMENT = 'CREATING_DOCUMENT'
export const CREATING_SHIPPING_TO = 'CREATING_SHIPPING_TO'
export const CREATING_SHIPPING_FROM = 'CREATING_SHIPPING_FROM'
export const CREATING_TRACK = 'CREATING_TRACK'
export const TRACKING_ERROR = 'TRACKING_ERROR'
export const SHIPMENT_CREATED = 'SHIPMENT_CREATED'